# Generated by Django 4.1.1 on 2022-09-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
